name-template: 'v${{ steps.generate_notes.VERSION }}'
tag-template: 'v${{ steps.generate_notes.VERSION }}'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
    ## What’s Changed

    $CHANGES

    ## Contributors
    Thanks to the following people who contributed to this release:
    $CONTRIBUTORS