exclude: .devcontainer|.vscode
repos:
# general
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
    exclude: (\.ipynb|devcontainer.json)$
  - id: check-yaml
  - id: pretty-format-json
    exclude: (\.ipynb|devcontainer.json)$
    args:
    - --autofix
    - --no-sort-keys
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: detect-private-key
  - id: check-added-large-files
    args: [--maxkb=4000]
    exclude: images/ui_example.gif|src/api/staged_model/default.torchscript
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
# python
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
    args: [--recursive, --in-place, --wrap-summaries, '88', --wrap-descriptions, '88']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.9
  hooks:
  - id: ruff
    types_or: [python, pyi, jupyter]
  - id: ruff-format
    types_or: [python, pyi, jupyter]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    args: [--check-untyped-defs, --non-interactive, --install-types, --no-namespace-packages]
    additional_dependencies: [types-setuptools]
# docker
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  - id: hadolint
# jupyter notebooks
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
  - id: nbstripout
# html
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
  - id: prettier
    files: \.(html|css|js|jsx)$
# system commands
- repo: local
  hooks:
  - id: taplo
    name: taplo (format toml)
    entry: find . -maxdepth 1 -name '*.toml' -exec taplo format --option indent_string="    " {} \;
    language: system
    pass_filenames: false
  - id: dockerignore
    name: dockerignore
    entry: echo "# This file is autogenerated by pre-commit from .gitignore do not edit" > .dockerignore && cat .gitignore >> .dockerignore
    language: system
    pass_filenames: false
