test:
	@pre-commit run --all-files

deploy:
	cdk bootstrap
	cdk deploy --require-approval never

p2t:
	@python utils/project_to_text.py

dockerignore:
	@echo "# This file is autogenerated by pre-commit from .gitignore do not edit" > .dockerignore
	@cat .gitignore >> .dockerignore

build-local:
	@echo "Building Docker image and running container"
	@docker image build --platform linux/arm64 -t lambda -f lambda/Dockerfile .
	@docker container run -p 9000:8080 lambda

invoke-local:
	@curl -X POST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
