test:
	@pre-commit run --all-files

e2e:
	@docker compose -f tests/api/docker-compose.yaml up --build --abort-on-container-exit

p2t:
	@python utils/project_to_text.py

dockerignore:
	@echo "# This file is autogenerated by pre-commit from .gitignore do not edit" > .dockerignore
	@cat .gitignore >> .dockerignore

run:
	@python -m api.api

build:
	@docker image build --platform linux/arm64 -t api -f api/Dockerfile .
	@docker container run -p 8080:8080 api

invoke:
	@curl -X POST http://localhost:8080/2015-03-31/functions/function/invocations -d @event.json

deploy:
	cdk bootstrap
	cdk deploy --require-approval never
