test:
	@pre-commit run --all-files

p2t:
	@python utils/project_to_text.py

dockerignore:
	@echo "# This file is autogenerated by pre-commit do not edit" > .dockerignore
	@cat .gitignore >> .dockerignore