[tool.poetry]
name = "example-cdk"
version = "0.1.0"
description = ""
authors = ["Alexander Lewzey <a.lewzey@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.1"
pytest = "^8.2.2"
aws-cdk-lib = "^2.147.0"
constructs = "^10.3.0"

[tool.poetry.group.lambda.dependencies]
requests = "^2.32.3"

[tool.poetry.group.app.dependencies]
aws-cdk-lib = "^2.147.0"
constructs = "^10.3.0"

[tool.poetry.group.other.dependencies]
ipykernel = "^6.29.4"
pathspec = "^0.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true


[tool.ruff]
select = [
    "A", # Pyflakes: general checks
    "B", # pycodestyle: pycodestyle checks
    "C", # mccabe: complexity checks
    # "D",  # pydocstyle: docstring style checks
    "E", # pycodestyle: pycodestyle errors
    "F", # pyflakes: unused imports, variables, etc.
    "I", # isort: import sorting
    "N", # pep8-naming: naming conventions
    "S", # bandit: security checks
    "W", # pycodestyle: pycodestyle warnings
]
ignore = [
    "S101", # Ignore use of assert detected
    "S108", # ignore use of tmp
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
]
fix = true
