# hadolint global ignore=DL3045,DL3013
# container that acts as client in the end-to-ends tests
FROM python:3.12-bullseye

COPY . .

RUN pip install uv --no-cache-dir && \
    uv venv && \
    uv sync --group test

# Install dockerize
RUN curl -LO https://github.com/jwilder/dockerize/releases/download/v0.7.0/dockerize-linux-amd64-v0.7.0.tar.gz && \
    tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.7.0.tar.gz && \
    chmod +x /usr/local/bin/dockerize
